### ISSUE TITLE
Does not work with more than one map on a page.

### ISSUE THREAD

**Issue by apiening** [jweiland-net/maps2#1]
Really nice extension, I like the ability to display multiple points on the map and the overall customizability.

I tried to add two plugins / maps on one page, but only the first one was displayed. I want to display the location of two sites in different cities.

It looks like this happens because the initial DIV container is rendered always with the same ID. Since the JS picks the container because of this ID, only the first one is chosen. Maybe it is possible to add the content element ID as a suffix to the ID of the div container and change the JS so that it reverences it?

**Comment by froemken** [comment]
With the patch from today I found a pretty cool solution for that. Have fun :-)
