### ISSUE TITLE
Custom POI Marker

### ISSUE THREAD

**Issue by stmllr** [jweiland-net/maps2#10]
As a designer
I want to use my custom image as marker
In order to apply corporate design in the map

Google Maps API v3 allows you to use a custom image as marker:

``` javascript
marker = new google.maps.Marker({
    (...),
    icon: 'http://path/to/image.png'
});
```
https://developers.google.com/maps/documentation/javascript/markers

It would be nice to configure the marker image through TYPO3 settings.

**Comment by stmllr** [comment]
btw. nice extension, it "just works" and is self-explaining.

**Comment by froemken** [comment]
Please go into a sys_category record. This extension creates a new field marker_icon to this table. Assign all you markers to that category and they all will get your CI Icon

**Comment by stmllr** [comment]
Thanks. That works! However it looks like the size is fixed to 25x40px https://github.com/jweiland-net/maps2/blob/master/Resources/Public/JavaScript/Maps2.js#L304

I'd prefer to use the default size of the icon. What do you think?
