### ISSUE TITLE
Google Maps, Zoom problem

### ISSUE THREAD

**Issue by SebZar** [jweiland-net/maps2#103]
Hi,
we've created some entries with a category assigned and included them in new maps2 element.

Everything looks fine, but setting the of the default zoom (settings.zoom) does not work. 
The map is always zoomed to show all entries.

e.g.
When there are two entries, one in the USA and one in Europe, the map is zoomed out.
When there are tow entries in Europe, the map is zoomed in.

Version 5.1.0

Please take a look.

Thanks in advance
Sebastian

**Comment by froemken** [comment]
Hello @SebZar 

that is absolutely correct. The default zoom ist only possible with one PoiCollection. If you are show many PoiCollections of a category we are using the BoundedBox-Feature of Google Maps or OpenStreetMap to zoom out to show all PoiCollections.

Nice greetings 

Stefan

**Comment by froemken** [comment]
In Plugin you have to either set one PoiCollection OR define a category to show multiple PoiCollections. It is not possible to leave them empty and hope that all PoiCollections of a StorageFolder will be displayed.
But you're not the only one having this problem...maybe this would be good feature for one of the next versions.

Stefan

**Comment by SebZar** [comment]
Okay, thank you.

**Comment by froemken** [comment]
I have just implemented a new option called forceZoom. I will upload this version today. Version 5.2.0.

**Comment by froemken** [comment]
Oh yes...with new version you can show all POIs of a defined storage folder.

**Comment by froemken** [comment]
New version 5.2.0 will be available in TER within the next 15 minutes:

https://extensions.typo3.org/extension/maps2/

Have fun

Stefan

**Comment by SebZar** [comment]
Perfect, thank you very much!
