### ISSUE TITLE
Op-In for google-maps

### ISSUE THREAD

**Issue by stephangrass** [jweiland-net/maps2#106]
Do you plan adding an opt-in feature for google-maps in your extension?

Thanks
Stephan

**Comment by froemken** [comment]
It‘s already there: https://github.com/jweiland-net/maps2/blob/master/ext_conf_template.txt#L14
You will find this Configuration in ExtensionManger or in SettingsModule, if you’re working with TYPO3 9

You can decide, if you want to safe activation as cookie or in browser session

Stefan

**Comment by stephangrass** [comment]
Ooops ...
Thanks!
