### ISSUE TITLE
Make the upgrade wizard work for CMS8 as well

### ISSUE THREAD

**Issue by metiny** [jweiland-net/maps2#109]
PHP	7.0.28
TYPO3 8.7.26
Maps2 5.20

Hello Stefan,
after Installation of MAPS2, it is not possible to start Upgrade Wizard in install Tool:
	
```
Detected Fatal Error
Interface 'TYPO3\CMS\Install\Updates\UpgradeWizardInterface' not found in .../typo3conf/ext/maps2/Classes/Update/MoveOldFlexFormSettingsUpdate.php on line 28
```
Solution is the same like here (tested):
https://github.com/Yoast/Yoast-SEO-for-TYPO3/commit/34e90eb66e06bf6638b66da9d1615c5e57c318d2

Many Thanks
Metin

**Comment by froemken** [comment]
Hi @metiny 

oh no! I saw that TYPO3 uses UpgradeWizardInterface instead of AbstractUpdate and I thought this interface is on board since years. Nope...my fault. I will release a new version.

Thank you for your report

Stefan

**Comment by froemken** [comment]
Hello @metiny 

I have just pushed a new version to master which solves your problem.

Thank you for your report

Stefan
