### ISSUE TITLE
Setting size of the POI marker

### ISSUE THREAD

**Issue by stmllr** [jweiland-net/maps2#11]
Currently marker image size has a fixed size of 25x40px set through `scaledSize` in https://github.com/jweiland-net/maps2/blob/master/Resources/Public/JavaScript/Maps2.js#L304

I'd suggest to make the size either configurable in sys_category beside the marker image and/or set the scaledSize property by using the width/height of the custom marker image size.

**Comment by stmllr** [comment]
Ping me if you need PR.

**Comment by froemken** [comment]
Only an idea:
I change the textbox for image path in sys_category to original FAL IRRE record. In that case TYPO3 will automatically read the image size. I copy these sizes and transfer them into my JS.

What would you think?

**Comment by stmllr** [comment]
Perfect

**Comment by froemken** [comment]
Hello @stmllr 

We have changed the image integration completely. Now it's FAL based and you can assign image sizes by ExtConf, sys_category and PoiCollection. Further you can assign the exact Position of the image.

Have fun

Stefan
