### ISSUE TITLE
'my_db.tx_extbase_domain_model_filereference' doesn't exist

### ISSUE THREAD

**Issue by stephangrass** [jweiland-net/maps2#110]
Sometimes we get the error Table 'my_db.tx_extbase_domain_model_filereference' doesn't exist, when trying to open a maps record in the backend. Clearing all caches will 'repair' this.

Here the full error-message:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1472074485: Table 'my_db.tx_extbase_domain_model_filereference' doesn't exist | TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException thrown in file /.../typo3cms/typo3_src-9.5.6/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php in line 375. Requested URL: https://domain.de/typo3/index.php?route=%%2Fajax%%2Fmaps2%%2Finsert%%2Froute&token=--AnonymizedToken--&tx_maps2_maps2%%5BobjectName%%5D=InsertRoute&tx_maps2_maps2%%5Bhash%%5D=70bc48be27cc5bb5b429ff1227669288e208b9b5&tx_maps2_maps2%%5Barguments%%5D%%5Buid%%5D=97&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B0%%5D=51.232787%%2C6.818566&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B1%%5D=51.232765%%2C6.818786&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B2%%5D=51.232637%%2C6.818751&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B3%%5D=51.232655%%2C6.818607&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B4%%5D=51.232683%%2C6.818438&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B5%%5D=51.232025%%2C6.818247&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B6%%5D=51.232001%%2C6.81841&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B7%%5D=51.23183%%2C6.818361&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B8%%5D=51.231814%%2C6.81851&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B9%%5D=51.232057%%2C6.818588&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B10%%5D=51.232056%%2C6.818589&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B11%%5D=51.232074%%2C6.818438&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B12%%5D=51.231831%%2C6.818364&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B13%%5D=51.231812%%2C6.818517&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B14%%5D=51.232058%%2C6.81859&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B15%%5D=51.232078%%2C6.818433&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B16%%5D=51.232659%%2C6.818603&tx_maps2_maps2%%5Barguments%%5D%%5Broute%%5D%%5B17%%5D=51.232666%%2C6.818525

**Comment by stephangrass** [comment]
Or this one:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1472074485: Table 'my_db.tx_extbase_domain_model_filereference' doesn't exist | TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException thrown in file /.../typo3cms/typo3_src-9.5.6/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php in line 375. Requested URL: https://domain.de/typo3/index.php?route=%%2Frecord%%2Fedit&token=--AnonymizedToken--&edit[tx_maps2_domain_model_poicollection][97]=edit&returnUrl=%%2Ftypo3%%2Findex.php%%3Froute%%3D%%252Fweb%%252Flist%%252F%%26token%%3Df0b999965fd45f536aced25dd7d95046cbaf1925%%26id%%3D70%%26table%%3Dtx_maps2_domain_model_poicollection%%26imagemode%%3D1

**Comment by froemken** [comment]
Hi @stephangrass 

I know this error from other extensions and it's a problem when ext_typoscript_setup.typoscript of EXT:extbase could not be loaded or was overridden.

On the other side your posted link is very long. Isn't there a limitation of letter in GET requests? 4000...6000 letters? Seems that the link was cutted and produces this problem. Can you send me the amount of pois you have created on the map? If this is really a problem I will change request to POST.

Thank you for your report.

Stefan

**Comment by stephangrass** [comment]
Hi Stefan,

the site is hosted by jweiland ;-) I don't know, if there there are limitations of letters in GET requests.

At the moment there are 115 pois (and also areas) on the map. But may be up to 200 in future ...

**Comment by stephangrass** [comment]
Hi Stefan,

at the moment there are 115 pois (and also areas) on the map. But may be up to 200 in future ...

**Comment by stephangrass** [comment]
But the problem occur only sometimes. I can't reproduce it. And clearing the cache will help for a while.

**Comment by stephangrass** [comment]
Hi Stefan,
any idea for this issue? 

After getting this error in the backend, also the frontend will be crashed with an error like

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1472074485: Table 'my_db.tx_extbase_domain_model_filereference' doesn't exist | TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException thrown in file /.../ttypo3cms/typo3_src-9.5.6/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php in line 375. Requested URL: https://www.mysite.de/whatever/

**Comment by stephangrass** [comment]
Hi Stefan,
can you tell, when you can solve the problem? May be, as you said, change request to POST will help.

Stephan

**Comment by froemken** [comment]
I have just uploaded maps2 in version 6.0.1. I'm now using POST requests instead of GET. Hope it helps.

**Comment by froemken** [comment]
Hello @stephangrass 

I just found out that false table name comes directly from Extbase Cache. I'm just searching which process stores this wrong entry.

I keep you informed.

Stefan

**Comment by froemken** [comment]
Hello @stephangrass 

with implementing infoWindowImages feature the extbase methods in our Ajax requests don't know the configuration of `config.tx_extbase` anymore and write a false mapping of FileReference to tablename mapping into extbase cache.
While reloading the BE form the false mapping will be reloaded from cache and Extbase tries to find files from table tx_extbase_domain_model_filereference.

I have rewritten our Ajax Calls completely to use native Doctrine Queries which don't need a config.tx_extbase configuration.

I'm just uploading version 7.0.0.

Nice greetings

Stefan
