### ISSUE TITLE
Trouble with translated PoiCollection Infowindows

### ISSUE THREAD

**Issue by Schweriner** [jweiland-net/maps2#113]
I'm having a problem using TYPO3 9.5.7 and Maps2 5.2.0 with the InfoWindows of PoiCollections.
When translating those records, in the backend the preview of the Infowindow is displayed correctly translated. But in the frontend the default languages Infowindow-Content is displayed.

I figured out, that the record translations are fetched correctly in the frontend but the property Infowindow stays in the default language.
I was able to solve the problem only by adding the allowLanguageSynchronization to the TCA which allows me to select, which language in the field will be used (default or the translated version). I though when there is no selection, by default the shown content will be used, but maybe there is a problem when building up the field with the extensions own InfoWindowCkeditorElement - RenderType?

However this TCA works for me:
```
'info_window_content' => [
            'exclude' => true,
            'label' => 'LLL:EXT:maps2/Resources/Private/Language/locallang_db.xlf:tx_maps2_domain_model_poicollection.info_window_content',
            'config' => [
                'type' => 'text',
                'renderType' => 'maps2InfoWindowContent',
                'cols' => 80,
                'rows' => 15,
                'softref' => 'rtehtmlarea_images,typolink_tag,images,email[subst],url',
                'enableRichtext' => true,
                'richtextConfiguration' => 'default',
                'behaviour' => [
                    'allowLanguageSynchronization' => true
                ],
            ],
        ],
```

**Comment by froemken** [comment]
Hello @Schweriner 

thank you for these issue reports. That was a great hint regarding InfoWindow Caching. One of my colleagues told me about that, but I can't reproduce that, but yes of cause, the language UID should be part of the Cache-entry.

Next week I'm on holiday, so it needs some time until I can fix that.

Stefan

**Comment by froemken** [comment]
Hello @Schweriner 

I have just uploaded maps2 version 6.0.0 which should solve that problem.
It is a breaking change as I have to remove cacheIdentifier property from all Cache ViewHelpers. Please have a look into update notes in documentation, if you have your own InfoWindowContent-Template.

Stefan
