### ISSUE TITLE
Ajax-Call for explicitAllowMapProviderRequests 

### ISSUE THREAD

**Issue by joeschi** [jweiland-net/maps2#118]
It would be great to have an ajax-call instead of form submit while giving the permision to load the map from Google.

**Comment by froemken** [comment]
Hello @joeschi 

Currently I don't see a possibility for that cool feature. With first view we can not add any JavaScript libraries from google servers. With a click on "activate" we reload complete site to re-parse TypoScript and its conditions to add the needed JavaScript libraries from Google to page footer. 

Maybe you can add a section/anker to the activation link with the Content Element UID of our plugin in fluid template. In most cases this should be something like  #c123
So, after clicking the link the page should scroll down back to our plugin again.

Stefan

**Comment by froemken** [comment]
Hello @joeschi 

on current master I have added a new TypoScript setting which is activated by default:

```
plugin.tx_maps2 {
  settings {
    overlay {
      link {
        addSection = 1
      }
  }
}
```

It is not an Ajax call, but should help to solve your problem.

Stefan
