### ISSUE TITLE
Update condition syntax

### ISSUE THREAD

**Issue by garfieldius** [jweiland-net/maps2#119]
The condition in file *Configuration/TypoScript/GoogleMaps/setup.txt* causes a lot of deprecation warnings. For installations running on TYPO3 v9.4+, the new Synatx should be used. A custom provider can be added as described in <https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/TypoScriptSyntax/Syntax/Conditions.html#custom-conditions-with-symfony-expression-language>.

I can create a PR for this, but that might take some time before I get to do so.

**Comment by froemken** [comment]
Hello @garfieldius 

I always try to support 2 TYPO3 versions. Currently TYPO3 8.7 and 9.5 are supported. As TYPO3 8 don't know new Symfony Syntax and don't know your mentioned hook to register new Symfony Conditions I can't implement this cool feature. I have to wait for TYPO3 10. With this switch I will remove support for TYPO3 8 and of cause I will switch to Symfony Expressions then.

PS: If you switch to LIVE/Production Environment you don't get any deprecation messages.

Stefan

**Comment by froemken** [comment]
Hello @garfieldius 

I'm just working on a new release for maps2 without TYPO3 8 compatible. Version 9.0.0 will be TYPO3 9 and 10 compatible. With this release I have completely switched over to Symfony Expression.

Stefan
