### ISSUE TITLE
maps2/Resources/Private/Templates/AllowMapForm.html

### ISSUE THREAD

**Issue by mixedpixels** [jweiland-net/maps2#130]
Typo in line 6  {settings.mapHeigt} should be {settings.mapHeight}?

Please ad title tag to link in line 12.

**Comment by froemken** [comment]
Hello @mixedpixels 

thank you for this issue. I have remove the mapWidth and mapHeight part in template completely.

I have just pushed version 5.3.1 to GitHub which will be available in TER soon.

Stefan
