### ISSUE TITLE
Exeption in 6.0.0

### ISSUE THREAD

**Issue by t3easy** [jweiland-net/maps2#133]
Version 6.0.0 throws an exeption:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to JWeiland\Maps2\ViewHelpers\ConvertToJsonViewHelper::getPoiCollectionsAsJson() must be of the type array, object given

TYPO3 8.7.28
PHP 7.2

**Comment by froemken** [comment]
Hello @t3easy 

wow thank you for your help. My fault, I was too fast with implementing strict_types in our ViewHelpers and have tested with only one PoiCollection.
I have just uploaded version 6.0.1 which solves this problem.

Stefan

**Comment by t3easy** [comment]
Thank you!
