### ISSUE TITLE
Areas are not saved

### ISSUE THREAD

**Issue by stephangrass** [jweiland-net/maps2#135]
Using maps2 6.0.1 drawn areas (and routes) in the configuration map will not be saved.
I get no javascript error, but a lot of warnings (reference errors).

Can anyone reproduce this behaviour?

Stephan

**Comment by froemken** [comment]
Hello Stephan,

I found that problem. I have switched over to POST requests in past and modified AjaxController accordingly, but that controller is not used anymore. So, yes, I have updated the wrong code.

I'm just working on a new version where I will remove the old code and update the correct AjaxRequest class now ;-)

Stefan

**Comment by froemken** [comment]
Hello @stephangrass 

I have just release version 7.0.1. Hope it helps.
Thank you for your support.

Stefan
