### ISSUE TITLE
Toggle scrollWheelZoom in OSM layer

### ISSUE THREAD

**Issue by andreasfernandez** [jweiland-net/maps2#136]
Google Maps allows to disable / enable zooming via scroll wheel. If OpenStreetMap is used, such option is missing. However, Leaflet supports this by setting `scrollWheelZoom: false|true`.

**Comment by froemken** [comment]
Hello Andreas,

I have just released version 6.1.0 where this option was implemented for OSM. Have fun.
As this option was moved from sheet sGoogleMaps to sMapOptions you should execute Update Wizard in Installtool before.

Stefan
