### ISSUE TITLE
Timeout at OpenStreetmap request

### ISSUE THREAD

**Issue by wowaTYPO3** [jweiland-net/maps2#142]

**Comment by mixedpixels** [comment]
see also: http://urbansketchers-stuttgart.de/

**Comment by froemken** [comment]
Could you please try adding "async" to JavaScript?

https://www.mediaevent.de/javascript/programm-struktur.html

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/7.1/Feature-28382-AddAsyncPropertyToJavaScriptFiles.html

**Comment by froemken** [comment]
Hello,

I currently can not reproduce this issue. If you have further information for me please re-open this issue.

Stefan
