### ISSUE TITLE
Filters for area, routes and radii not working

### ISSUE THREAD

**Issue by imminger** [jweiland-net/maps2#147]
The category-based selection and the filter checkboxes beneath the map are a great feature. However, there might be a bug: 

When selecting by category area, routes and radius are displayed in the frontend. However, the checkbox beneath the map has no effect on them - it only works for POIs.

![Filter](https://user-images.githubusercontent.com/15834641/70421352-f7d45f00-1a69-11ea-8e5c-2b8eb9ff6b2b.png)
_All checkboxes are disabled - but areas, routes and radii are still visible_

**Comment by froemken** [comment]
Hello @imminger 

thank you for your help. I just have pushed a new version to dev-master which solves this issue. It will be released with upcoming version 10.0.0.

Stefan

**Comment by imminger** [comment]
Awesome, thank you. I am looking forward to V10 🎉
