### ISSUE TITLE
Info window for area, routes and radii [Feature]

### ISSUE THREAD

**Issue by imminger** [jweiland-net/maps2#148]
Hello,

Maps2 is great. However, I'm missing one feature: would it be possible to open the info window when the user clicks on an area, route or radius? Seems like this is currently not supported by the extension. 

Thanks for developing this extension.

**Comment by froemken** [comment]
Hello @imminger 

jep, it was not possible...until now. There was another customer how needs it. Your lovely cool new feature is available since version 9.1.0.

Have fun

Stefan

**Comment by imminger** [comment]
That's awesome. Thank you! 

Maps2 has a good feature set and is easy to use 👍
