### ISSUE TITLE
How to add a custom marker?

### ISSUE THREAD

**Issue by Toccamonium** [jweiland-net/maps2#16]
Hi,
Would be cool to see in the design tab a extra field where to set the path to my own marker, which adapts the company color. Thanks for this nice extension.

regards
Florian

**Comment by froemken** [comment]
Have you seen the image path configuration in system categories (sys_category)? So, you can assign an image path to a category and each POI which was assigned to this category will automatically displayed with your image.

**Comment by Toccamonium** [comment]
Do you have an example how it should look like and where to do it exactly? Thanks indeed.
Really cool would be to add another input to the general tab where the editor can select an image directly from the fileadmin/user_upload folder :)

**Comment by froemken** [comment]
Hello @Toccamonium 

we have updated our maps2 to use images in PoiCollection and sys_category records. I think now it is much easier to handle images.

Further you can set image sizes and positions

Have fun

Stefan
