### ISSUE TITLE
Hook für Inhalt Info-Window

### ISSUE THREAD

**Issue by wowaTYPO3** [jweiland-net/maps2#160]
Fremddatensatz als Array der POI-Collection hinzufügen.

**Comment by josefglatz** [comment]
You have at least the option to overwrite the fluid template and use a custom VH to get some other related record(s)

**Comment by froemken** [comment]
@josefglatz I'm not using VHs to collect further data. This is part of the Repository or the DomainModel. Collecting data with VHs is the last option for me, if I don't know other way.

@wowaTYPO3 I have added a solution for your issue with maps2 version 9.2.0. Simple loop over {poiCollection.foreignRecords} or use f:groupedFor as described in documentation, to reduce the related records to one specific table.

Thank you for your help

Stefan

**Comment by josefglatz** [comment]
Thank you Stefan for adding such functionality. This makes it really easy now. Didn't think of such a possibility (to contribute)
