### ISSUE TITLE
Hardcoded http call for tiles png

### ISSUE THREAD

**Issue by Isaegenuet** [jweiland-net/maps2#167]
Could you please change the hardcoded http call

https://github.com/jweiland-net/maps2/blob/9b8b34a89099f92ba85450d00131a3b50a33bb02/Resources/Public/JavaScript/OpenStreetMapModule.js#L16

Thank you in advance for your effort.

René

**Comment by froemken** [comment]
Hello @Isaegenuet 

thank you for reporting this issue, I have changed that to scheme of current request. So, if you open your BE over https: the Tiles of OpenStreetMap will be loaded over https:, too. Else http:

I have just released Version 9.0.1

Stefan
