### ISSUE TITLE
Unsupported or non-existing property name "categories" used in relation matching.

### ISSUE THREAD

**Issue by rasgor** [jweiland-net/maps2#17]
Dear Stefan,

first of all .. thank you for your great extensions :)

I'am using TYPO3 8.7.1 and included the maps2 extension with the Google Maps default view.
All other necessary settings are also made but after a while TYPO3 throws following Exception:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1327065745: Unsupported or non-existing property name "categories" used in relation matching. | TYPO3\CMS\Extbase\Persistence\Generic\Exception\RepositoryException thrown in file /var/www/_typo3/typo3_src-8.7.1/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbQueryParser.php in line 371. Requested URL: http://....`

The only way to get easily rid of this error for a short time is to clear all caches in the TYPO3-Backend ... until the error occurs again.

I hope you have any kind of idea on how to solve this strange behaviour.

**Comment by froemken** [comment]
Hello @rasgor 

I just have uploaded a new version of maps2 to Github where I have moved many TCA entries from ext_tables.php to TCA/Overrides/*. At that place TCA can be cached.
As I can't reproduce that error it would be cool, if you can give me a short reply if it works now.

Stefan

**Comment by rasgor** [comment]
Thank you for your fast response and code changes ... I've uploaded the changes an will report if the error occurs again.

**Comment by rasgor** [comment]
After giving it a one day trial ... I can report that the error is gone ... many many thanks.

@froemken is there any official documentation about the "TCA/Overrides/*" mechanism and the caching behaviour??

**Comment by froemken** [comment]
Perfect. Thank you for your feedback.
The documentation regarding Overrides you can find here: https://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/ExtendingTca/StoringChanges/Index.html#storing-in-the-overrides-folder
