### ISSUE TITLE
Embedding maps2 as a content element in news

### ISSUE THREAD

**Issue by Epoche-Napoleon** [jweiland-net/maps2#173]
On the detail page of News there is still a small problem that has only occurred due to your bug fixing.

On a lot of news articles I have additionally included Maps2.  When you enter the page for the first time, a GDPR hint is shown instead of the Googlemap and the map is only displayed after clicking on it. 

The map is reloaded when the page is reloaded. 

For example here:

[https://composer.epoche-napoleon.net/nachricht/2020/juni/27/schiller-museum-bauerbach-oeffnet-wieder-nach-umfangreicher-sanierung.html](https://composer.epoche-napoleon.net/nachricht/2020/juni/27/schiller-museum-bauerbach-oeffnet-wieder-nach-umfangreicher-sanierung.html)

After activation, the following URL is called up.

[https://composer.epoche-napoleon.net/nachricht.html?tx_maps2_maps2%5BmapProviderRequestsAllowedForMaps2%5D=1&cHash=868aa8df4b6ccaf685caaafdf910c40e](https://composer.epoche-napoleon.net/nachricht.html?tx_maps2_maps2%5BmapProviderRequestsAllowedForMaps2%5D=1&cHash=868aa8df4b6ccaf685caaafdf910c40e)

And instead of the news, the note "This article is no longer available".

The map is displayed activated when the pages or other news pages are called up again.

I am currently working on the following workaround: 
I have deactivated 
`basic.explicitAllowMapProviderRequests `
and 
`activated basic.explicitAllowMapProviderRequestsBySessionOnly `

**Comment by Epoche-Napoleon** [comment]
Hi Stefan,
thanks to the help of NITSAN I was able to fix the file MapService.php accordingly and now the redirection to the right news item works. 

[Link zum GIST](https://gist.github.com/Epoche-Napoleon/57f534bc9dc46f51bcc547a305b9de5f)

**Comment by froemken** [comment]
Hello @Epoche-Napoleon 

thank you for your help to make maps2 a better extension. I just have uploaded a new version 9.3.9 to TER and Packagist which solved that issue. I have looked at your link/patch, but that will solve the problem in some but not all cases.

Sorry for the delay

Stefan
