### ISSUE TITLE
Maps2 breaks Extension Manager

### ISSUE THREAD

**Issue by zege-at** [jweiland-net/maps2#175]
I'm using Typo3 10.4.6 with PostgreSQL backend. After installing Maps2 i cannot open the extension manager. I get following error:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'SHOW FULL COLUMNS FROM `sys_category`': SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "FULL" LINE 1: SHOW FULL COLUMNS FROM `sys_category` ^ | Doctrine\DBAL\Exception\SyntaxErrorException thrown in file /var/www/typo3/typo3_src-10.4.6/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php in line 54. Requested URL: https://xxxx/typo3/index.php?route=%%2Fmodule%%2Ftools%%2FExtensionmanagerExtensionmanager&token=--AnonymizedToken--&tx_extensionmanager_tools_extensionmanagerextensionmanager%%5Baction%%5D=index&tx_extensionmanager_tools_extensionmanagerextensionmanager%%5Bcontroller%%5D=List

After manually removing Maps2 everything works as expected.
![Bildschirmfoto von 2020-08-07 14-02-18](https://user-images.githubusercontent.com/30209747/89643698-a610fc80-d8b6-11ea-9983-288c38e3f0bd.png)

**Comment by froemken** [comment]
Hello @zege-at 

I have just released maps2 in version 9.3.7 which is PostgreSQL compatible.

Hope it helps.

Have a cool start into this new week

Stefan
