### ISSUE TITLE
Feature request for other Consent tools, e.g. Klaro

### ISSUE THREAD

**Issue by heyse-dc** [jweiland-net/maps2#178]
It would be nice to have a trigger for the integration into other Consent tools e.g. Klaro.

**Comment by froemken** [comment]
I have added a manual how to integrate klaro:
https://github.com/jweiland-net/maps2/blob/master/Documentation/FAQ/Index.rst

**Comment by DTM-TYPO3** [comment]
Hello,
I'm using the consent EXT mindshape_cookie_consent [()](https://extensions.typo3.org/extension/mindshape_cookie_consent) and tried to add a trigger for maps2 but without success.
Could you please integrate a trigger for mindshape?
Thanks in advance!
Stefanie
