### ISSUE TITLE
HTML Code in infoWindow

### ISSUE THREAD

**Issue by taunusweb** [jweiland-net/maps2#18]
Hi there,

in a TYPO3 8LTS Version I have a strange Behavior: The infoWindow shows the HTML-Code, I'm using the default infoWindowContent.html Template
![screenshot-maps2](https://user-images.githubusercontent.com/20698711/27506624-268399aa-58bc-11e7-8dfb-1126902a052f.jpg)

In A Version 7LTS it works as expected... I'm using latest jquery Version 3.2.1, but happens with Version 2 too.
See it live at:
[http://vorschau.mediphysis.de/index.php?id=4]( http://vorschau.mediphysis.de/index.php?id=4)

**Comment by rasgor** [comment]
Hey,

I ran into the same problem on latest TYPO3 8LTS and left out the caching mechanism in my overwritten template of InfoWindowContent.html.

There seems to be a problem with

 `maps2:cache.getCache`
`maps2:cache.setCache`

but I haven't figured out the problem yet.

**Comment by taunusweb** [comment]
O.K., I'm not a developer, can you give me a hint, how to get rid of the cache?

**Comment by froemken** [comment]
Seems the TYPO3 Core has switched the htmlspecialchar automatism for ViewHelpers from false to true. I have reactivated it with $escapeOutput = false in getCache ViewHelper now. I will push the new version right now to TYPO3 TER.

**Comment by rasgor** [comment]
Thanks a lot.
