### ISSUE TITLE
trim() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by andreasfernandez** [jweiland-net/maps2#192]
With (at least) PHP 7.4, it's not possible to edit map markers due to the following error:

```
(1/1) TypeError
trim() expects parameter 1 to be string, null given

in typo3conf/ext/maps2/Classes/Form/Element/ReadOnlyInputTextElement.php line 128
```

**Comment by froemken** [comment]
Hello @andreasfernandez 

I remember that problem and copied the content of TYPO3 InputTextElement back into my file. And on master I have removed strict_type from PHP Header. So, if this is really a problem we have a problem in TYPO3,  too:

https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/backend/Classes/Form/Element/InputTextElement.php#L156

Or you have a maps2 version where strict_type is still in PHP Header defined.

So, what would be the best way to solve that?

Stefan

**Comment by andreasfernandez** [comment]
Hi @froemken 

it seems the latest release (9.2.1) still has `declare(strict_types=1)` enabled. Yes, this issue will hit the TYPO3 Core as well once strict types are enabled in there as well.

However, I think solving the issue with a null coalesce operation is the smartest solution, please see PR #193 as well.

Kind regards
Andreas
