### ISSUE TITLE
Additional Javascript?

### ISSUE THREAD

**Issue by taunusweb** [jweiland-net/maps2#194]
Hi,
is it possible to embed some addition Javascript Code? I'd like to embed e.g. a "var polygonMask..." and don't know, how to do that. 
Thanks in advance and happy holidays
Uli

**Comment by froemken** [comment]
Hello @taunusweb 

all our JavaScript will be added by `page.includeJSFooterlibs` So you still have the possibility to add further JavaScript in behind with `page.includeJSLibs`.

I have never extended our JavaScript and add further code, but yes, I have though about that. As you can see I have added a global Variable called `$maps2GoogleMaps` in GoogleMaps2.js as array. For each maps2 Plugin I add the element to that array.
If you load your JavaScript behind our JavaScript you can loop through `$maps2GoogleMaps` and hopefully modify each individual maps2 element.

But as I told you, I have never tried it.

Stefan
