### ISSUE TITLE
"settings.activateScrollWheel = 1" is missing in Configuration/TypoScript/setup.txt

### ISSUE THREAD

**Issue by taunusweb** [jweiland-net/maps2#196]
Hi there,
to use this feature, I had to put the following lines in my setup, because it's missing in the file mentioned above and I wasn't able to deactivate the Scrollwheel 
```
plugin.tx_maps2 {
    settings {
       activateScrollWheel = 1
    }
} 
```
I'm not very familiar with Pull request, so i choose this way, hope, that's o.k.

**Comment by froemken** [comment]
Hello @taunusweb 

this settings has a low priority and will be overwritten by the same setting in the FlexForm of the Plugin. So, if you set activateScrollWheel to 0 in TypoScript, but to 1 in FlexForm of plugin, this setting will be true for frontend output.

But yes, you're right, this value isn't there in TypoScript, but I don't know if it really helps if I add it within one of the next versions.

Stefan

**Comment by taunusweb** [comment]
That's right, in the flexform it is set to "1" by default, so I added the line although to "1" in my TypoScript. Now my changes in the flexform have an effect, if I uncheck the Checkbox, the scrollwheel Zoom is disabled. Without this line in the TypoScript the flexform has no effect, the scrollwheel Zoom is always active and I can't disable it.

**Comment by froemken** [comment]
Hello @taunusweb 

Thank you for that hint. I will test that.

Stefan

Following is just for me:

The problem seems to be here: https://github.com/jweiland-net/maps2/blob/master/Classes/Controller/AbstractController.php#L51-L55

Create UnitTests to prevent that problem

**Comment by froemken** [comment]
Hello @taunusweb 

it seems that you have switched maps2 plugin between all these Plugin types CityMap, Maps2 and SearchWithinRadius. I just see, that I have forgotten to rename the FlexForm sheet `sDEFAULT` into `sDEF` 2 or 3 years ago. So now you have various values like minHeight, maxWidth twice in DB.

Please update to current dev-master or download version 9.3.11 from TER or composer and execute UpgradeWizard to update the settings in pi_flexform column of your tt_content records.

Have a nice start into this new week

Stefan
