### ISSUE TITLE
responsive maps2

### ISSUE THREAD

**Issue by gerweise** [jweiland-net/maps2#210]
![Bildschirmfoto 2021-03-31 um 10 24 38](https://user-images.githubusercontent.com/81701010/113170152-962f9980-9246-11eb-9492-a106432c9762.png)
the embedded map covers the offcanvas menu. Was it my fault? How can I change the z-index?

**Comment by froemken** [comment]
Hello @gerweise 

thank you for reporting this issue.
The only z-index I have found was in CSS of Leaflet. The css-file was configured here in TypoScript:

https://github.com/jweiland-net/maps2/blob/master/Configuration/TypoScript/OpenStreetMap/setup.txt#L9

So copy content of that css-file into your own SitePackage extension, adopt the z-index settings and override leaflet css-file with your own one in TypoScript.

Happy easter

Stefan
