### ISSUE TITLE
Feature Request: make info window optional for areas

### ISSUE THREAD

**Issue by rteitge** [jweiland-net/maps2#211]
Currently there is always a click event to open an info window on areas, I can't find any option to disable it.

**Comment by froemken** [comment]
Hello @rteitge 

thank you for your feature request.

This is a really really individual feature and I don't think that we will implement that as a useful feature for the whole community.
Either I have to implement a new column for poi_collection table where you can de-/activate that feature for each individual record or I have to add an option into TypoScript and/or Flexform to de-/activate infoWindows and page/plugin base.

But both solutions will not de-/activate your feature for just a specific collection_type like "area" or "route".

As discussed on #maps2 Slack Channel:

Create a copy of OpenStreetMap.js into your SitePackage extension and add an if around the onclick-event: https://github.com/jweiland-net/maps2/blob/2b9e54b01a7d0361317f42a59d25ca039487009f/Resources/Public/JavaScript/OpenStreetMaps2.js#L321

It should look something like:

```
if (poiCollection.collectionType !== "Area") || environment.settings.disableInfoWindow === 0) {
    ...onclick...
}
```

Now refer to your own JavaScript file like done here:

https://github.com/jweiland-net/maps2/blob/master/Configuration/TypoScript/OpenStreetMap/setup.txt#L15

Have a good start into the new week

Stefan
