### ISSUE TITLE
Localized info window not displayed

### ISSUE THREAD

**Issue by Hammer36** [jweiland-net/maps2#219]
I have localized my Maps2 records (original language: German) to English. Then I have localized the "Maps2: show map [maps2_maps2]" element, too. In the element's plugin options "Which marking should be shown? If there is a marking defined in website uri, that one has priority. [settings.poiCollection]" if have selected the localized Maps2 record.
However, the original German record is displayed when clicking on the POI  marker.

**Comment by Hobokens** [comment]
Hi @froemken ,
I can confirm the problem with TYPO3 10.4.20 and maps2 9.3.9.
Regards
Hobokens

**Comment by froemken** [comment]
Hello @Hammer36 @Hobokens 

thank you for your report. I have just released version 9.3.10 which solves that issue for Google and OSM

Stefan

**Comment by Hammer36** [comment]
Works perfect now. Thanx!

**Comment by Hobokens** [comment]
I gladly join the thanks.
