### ISSUE TITLE
Hidden POI - Point Marker missing - TYPO3 Backend

### ISSUE THREAD

**Issue by rasgor** [jweiland-net/maps2#221]
Maybe it's a matter of opinion but isn't it usefull to see the marker position on the map even if the POI is hidden? 

The marker disapears from the map if the POI is set to hidden. 

EXT:maps2/Classes/Form/Element/OpenStreetMapElement.php

Line 165:

`$poiCollection = $this->poiCollectionRepository->findByUid($uid);` 

This seems to be the problem. Same applies for the GoogleElement

Settings:
TYPO3 10.4.17  
maps2 9.3.7
map type osm

Best regards
Robert

**Comment by froemken** [comment]
You are right. Using Extbase in backend form is a bad idea ;-)
While my work upgrading maps2 for TYPO3 11 I have reduced extbase calls a lot. As you see in branch typo3_11_compatibility the PoiCollectionRepository has gone completely:

https://github.com/jweiland-net/maps2/blob/typo3_11_compatibility/Classes/Form/Element/OpenStreetMapElement.php#L132

I mark this problem as solved. It will be integrated with upcoming maps2 version 10.0.0.

Thank you for your report.

Stefan

**Comment by rasgor** [comment]
Tank you for your answer and improvements of this extension. Keep up the good work.
