### ISSUE TITLE
Geocode via Scheduler / CLI?

### ISSUE THREAD

**Issue by peerlight** [jweiland-net/maps2#226]
This is a feature wish: Geocode items with [collection_type] = point and [latitude]/[longitude] = 0 via Scheduler / CLI 

We would like to regularily batch import items and need to geocode them.

Additionally it could be possible to use imported optimized values from [configuration_map]-field to leave more readable values in [address]-field untouched; clear this field afterwards

**Comment by froemken** [comment]
Hello @peerlight 

I don't think that we will implement such a feature. OpenStreetMap writes "fair usage only", and there are limitations for Google Maps "Free Tier". With a scheduler task or CLI we would create a lot of requests to these services and limits could be reached which will block further requests for an hour or two. So, an editor can not create any further POIs within this timeout.

EXT:maps2 is designed as API at some places. Please add following to your importer:

```
$geoCodeService = GeneralUtility::makeInstance(GeoCodeService::class);
$position = $geoCodeService->getFirstFoundPositionByAddress($search->getAddress());
if ($position instanceof Position) {
    $latitude = $position->getLatitude();
    $longitude = $position->getLongitude():
    ...do whatever you want...
}
```

Have a nice evening

Stefan
