### ISSUE TITLE
sql error when creating new marker

### ISSUE THREAD

**Issue by Yahatix** [jweiland-net/maps2#23]
Ich glaube das es daher kommt weil in ext_tables.sql gesagt wird (``info_window_content text NOT NULL``) das das feld info_window_content vom typ text sein soll aber dieser typ keinen default wert haben kann. Aber typo3 8.7.3 will einen default wert haben.
![bildschirmfoto 2017-07-27 um 14 48 24](https://user-images.githubusercontent.com/21371842/28670826-bcc8b3a4-72da-11e7-851e-d48bf0210441.png)

**Comment by froemken** [comment]
Moin @Yahatix 

Danke für Deine Unterstützung.

Ich habe gerade eine Version in den master gepushed, in der ich dieses NOT NULL entfernt habe. TYPO3 selbst hat auch nicht mehr dieses NOT NULL im bodytext. 

Stefan
