### ISSUE TITLE
$config['radius'] is immediately overridden, please check this code fragment.

### ISSUE THREAD

**Issue by PeaceSfiSh** [jweiland-net/maps2#230]
This "error" was reported in the GoogleMapsElement and OpenStreetMapElement classes by the IDE.
`$config['radius'] = $poiCollection->getRadius();` could be deleted.

**Comment by froemken** [comment]
Good morning @PeaceSfiSh 

Thank you for this issue. I have just patched that in current master (currently broken because of TYPO3 11 upgrade, sorry).

Nice greetings

Stefan
