### ISSUE TITLE
Typo3 11 Compatibility

### ISSUE THREAD

**Issue by twurmehl** [jweiland-net/maps2#235]
When will maps2 (and also events2) be compatible with Typo3 11?

**Comment by froemken** [comment]
Hello @twurmehl 

there is already a working maps2 Version in our branch: https://github.com/jweiland-net/maps2/tree/typo3_11_compatibility
As I have no other TYPO3 11 compatible extensions here to test the API of maps2, I can't release it.

Currently I have nearly 10 further jobs to do on my list, before I can work on events2 again. But sorry, I can't give you a date.

I'm leaving the ticket open so others can see this status as well.

Stefan

**Comment by twurmehl** [comment]
Thank You very much! So i work with this branch and am looking forward to the compatible events2. No pressure ;) in the meantime I can work with Tyop3 10 on my productive Systems and update them as soon as events2 is ready.

**Comment by twurmehl** [comment]
With the typo3_11_compatibility version I get the following error in Typo3 11.5.3:
PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "maps2_cachedhtml" in /var/www/html/var/cache/code/core/ext_localconf_85ddb634473f9159318d809d1c315e0b581c8f9b.php line 1186
And the map in the frontent shows only a blue area.
![image](https://user-images.githubusercontent.com/56545341/143022981-a0377442-69ec-4352-8598-5e854c768256.png)
Any idea how to fix this?

**Comment by Oktopuce** [comment]
Witch version of PHP do you use. 
This bug is similar to many TYPO3 bugs in version 8.

**Comment by PhilippKuhlmay** [comment]
I get the same one: 
`PHP Warning: Undefined array key "maps2_cachedhtml" in /var/www/html/public/typo3conf/ext/maps2/ext_localconf.php line 54`
PHP 8.0.13
TYPO3 11.5.6

**Comment by froemken** [comment]
EXT:maps2 in version 10.0.0 is available for composer and in TER now.
TYPO3 9 compatibility was fully removed.
Version 10.0.0 supports PHP 7.4, 8.0, 8.1.
TYPO3 10.4 users with PHP 7.2 or 7.3 please use version 9.3.*
