### ISSUE TITLE
TYPO3 10 and Settings

### ISSUE THREAD

**Issue by SimonWpt** [jweiland-net/maps2#236]
I have the problem, that the settings in backend are not recognized. One problem seems to be this if-clause:
https://github.com/jweiland-net/maps2/blob/master/Classes/Controller/AbstractController.php#L52

I believe, this should be the correct query:
`if (is_string($value) && !empty($tsSettings['settings'][$setting])) {`

With this patch I can set i.e the `map.height` and `map.width`. But other settings like `Show full screen Control` are neverthless not recognized.

**Comment by froemken** [comment]
Hello @SimonWpt 

thank you for the access to your website...that helped a lot.
After executing the UpgradeWizards the mapWidht and mapHeight options are successfully transferred to the correct FlexForm sheet.

So these values should work again.

I'm sorry for fullScreen bug, but OSM does not support that. You can try to implement that feature with a leaflet plugin: https://github.com/brunob/leaflet.fullscreen

Stefan
