### ISSUE TITLE
Typo3 11 Compatibility composer install block

### ISSUE THREAD

**Issue by jschmietendorf** [jweiland-net/maps2#238]
After a composer install of Maps2 Maintenance > Analyze Database Structure throws an Ajax error "(1/1) #4 JsonException
Syntax error"
<img width="1002" alt="Bildschirmfoto 2022-01-19 um 10 19 17" src="https://user-images.githubusercontent.com/64953282/150101866-77eeccea-ceb5-4882-97aa-6b703ae710f8.png">
<img width="999" alt="Bildschirmfoto 2022-01-19 um 10 19 32" src="https://user-images.githubusercontent.com/64953282/150101930-3e874c0f-283a-45e1-9556-3b29a19b5b64.png">
<img width="1002" alt="Bildschirmfoto 2022-01-19 um 10 19 46" src="https://user-images.githubusercontent.com/64953282/150101998-e30179c7-38db-46b9-9562-d660986ed2b7.png">

TYPO3 11.5.5 | 11.5.6
"jweiland/maps2": "dev-typo3_11_compatibility"
/config/Maps2/Registry.json stays ALWAYS empty, when I try to save some configuration.

**Comment by froemken** [comment]
Hello @jschmietendorf 

thank you for testing the 11 branch for maps2.
I wonder about this error message as JSON_THROW_ON_ERROR was added with php 7.3.0. As TYPO3 11 needs at least PHP 7.4 and does not official support PHP 7.3 anymore (see: https://typo3.org/cms/roadmap). So, which PHP version you are using?

Nice greetings

Stefan

**Comment by jschmietendorf** [comment]
Hello Stefan,
we are using PHP 7.4.13.

Greetings
Jens

**Comment by froemken** [comment]
Hello @jschmietendorf 

Thank you for your help. I have found the issue. Creating the Maps2Registry with empty string throws an Exception. On current branch I fill Maps2Registry file with a valid decodable JSON string "{}".

Please delete config/Maps2/Registry.json, clear both caches, reload TYPO3 and it will work.

Nice greetings

Stefan

**Comment by froemken** [comment]
PS: I further have added the PHP requirements to compsoer and ext_emconf.php ;-)
