### ISSUE TITLE
cant add multiple markers

### ISSUE THREAD

**Issue by Yahatix** [jweiland-net/maps2#24]
Ich kann in typo3 8.7.3 nicht mehrere Point Of Interest Marker zu einer karte hinzufügen.
Man ersetzt immer den alten

**Comment by froemken** [comment]
Hallo @Yahatix 

um mehrere Marker auf einer Karte zu haben musst Du mit Kategorien arbeiten.
Erstell eine neue sys_category. Und weise einen oder mehrere Marker dieser Kategorie zu.
Dann im Plugin kannst Du sagen, zeige alle Marker der Kategory XY an.

Lieben Gruß

Stefan
