### ISSUE TITLE
[TYPO3 11] Google Maps is centered at wrong position

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/maps2#242]
The Google Maps is centered at a wrong position when showing at the location details page.
It seems that it is showing the positon Lat: 0.0000 / Lon: 0.0000.
(I am not using an API key for Google maps at the moment)

<img width="1367" alt="Bildschirmfoto 2022-02-23 um 10 27 15" src="https://user-images.githubusercontent.com/57705869/155292381-6f79f970-55b6-4162-b6b4-d252c92bc3d7.png">

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

"At the location detail page"? You mean the location page of EXT:events2, right?

I have just tested that scenario and it works without any problems. Have you updated the Location.html or, are you using the most current version of events2:

https://github.com/jweiland-net/events2/blob/typo3_11_compatibility/Resources/Private/Templates/Location/Show.html

**Comment by PhilippKuhlmay** [comment]
> Hello @PhilippKuhlmay
> 
> "At the location detail page"? You mean the location page of EXT:events2, right?
> 
> I have just tested that scenario and it works without any problems. Have you updated the Location.html or, are you using the most current version of events2:
> 
> https://github.com/jweiland-net/events2/blob/typo3_11_compatibility/Resources/Private/Templates/Location/Show.html

@froemken 
I mean the page which shows after I hit the link for the location (here "Sternwarte Presberg").
<img width="232" alt="Bildschirmfoto 2022-03-10 um 16 28 14" src="https://user-images.githubusercontent.com/57705869/157695487-96f7cb03-f28c-4467-a2ec-96bc5b1e6830.png">

I haven't modified any of the templates so it is still the default template. I am using the dev-typo3_11_compatibility branch for EXT:events2

I stil have this issue with the new maps2 version 10.0

**Comment by froemken** [comment]
Good morning @PhilippKuhlmay 

I just found the issue. Please use latest typo3_11_compatibility branch or update events2 Location/Show.html template and change partial to this line:

```
<f:render partial="Maps2/PoiCollection"
   section="showMap"
   arguments="{poiCollections: {0: location.txMaps2Uid}, override: {settings: {mapWidth: '100%', mapHeight: '300', zoom: '14'}}}" />
```

The problem was, that the partial expects `poiCollections` instead of just `poiCollection`.

Thank you for your help

Stefan

**Comment by PhilippKuhlmay** [comment]
Hi @froemken This works now, thanks.
