### ISSUE TITLE
[TYPO3 11] Open Street Map is not showing any images

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/maps2#243]
The Open Street Map at the Location details view is not showing any content. The whole map is missing and the frame is grey.

The console has a lot of 404 Errors for the images. 
`GET https://b.tile.openstreetmap.org/$15/$16386/$16384.png 404`

Without the `$` inside the link its working but it seems to has the wrong Lat/Lon as in Ticket #242 

this TS inside setup is working:
```
plugin.tx_maps2 {
  settings {
    mapTile = https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
  }
}
```

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

I know this problem. 2 or 3 years ago I have added following lines ;-)
https://github.com/jweiland-net/maps2/blob/master/Classes/Helper/SettingsHelper.php#L41

But with PoiCollectionWidget removal prepareSettings method was not called anymore. I have just added a new Service to prepare settings also in EnvironmentViewHelper.

Now it works again.

Stefan
