### ISSUE TITLE
[TYPO3 10] Problems with settings from Flexforms (e.g. mapWidth and mapHeight)

### ISSUE THREAD

**Issue by Kephson** [jweiland-net/maps2#244]
Hello Stefan,
we found some Problems in TYPO3 10.4 with the settings in the Plugin via FlexForms:
All the fields repeated in the different FlexForms configured in backend will use the value only from one of the FlexForms.
To explain it in detail:
- there are 3 Flexforms: CityMap.xml, Maps2.xml, Radius.xml and some settings in it like settings.mapWidth or settings.mapHeight
- the FlexForms uses same variables, eg. mapWidth and mapHeight
- when setting e.g. the map height in the showMap plugin, then it doesn't work; if you switch the plugin to CityMap, do the settings and switch back it works

I think the variables will be overwritten in $this->settings in Controller.
If you need some more information please contact me.

**Comment by froemken** [comment]
Good morning @Kephson 

thank you for your help. I just see that I have forgotten to rename FlexForm sheet `sDEFAULT` for plugin `citymap` and `searchwithinradius` to `sDEF` 2 or 3 years ago.

Please execute UpgradeWizard to update tt_content records with duplicate settings!!!

I have solved this issue on dev-master already and backported it also for version 9.3 (TYPO3 9 and 10 compatibility). You will find the new version at composer and TER.

Have a cool start into this new week

Stefan
