### ISSUE TITLE
Image for Info Window

### ISSUE THREAD

**Issue by renekreupl** [jweiland-net/maps2#25]
It would be great if in the InfoWindow tab the possibility for an image upload (FAL) would be given.
Almost always, customers want to enter a logo.

**Comment by webdev2027** [comment]
Hi, good point, rene. Same issue here ... an image inside the Marker-Popup would be nice! It's a RichTextarea, so I try to activate images for RTE, but it won't work. I can't test it with the ne `ckeditor`

**Comment by renekreupl** [comment]
Inline Images will work, but for Special Styling is ..... :)

**Comment by froemken** [comment]
Before I will allow images in rtehtmlarea or ckeditor I implement an additional field below editor where you can define one or more images on your own and you can better style them in Fluid-Template as in Editor.

Deal?

Stefan

**Comment by renekreupl** [comment]
Great Stefan! Thanks, that is a good deal ;)

**Comment by froemken** [comment]
The new feature is just in Travis. You can set width/height via TypoScript or directly in Fluid. New version will be 4.1.0
