### ISSUE TITLE
Upgrade Wizard throws error with "not existing table"

### ISSUE THREAD

**Issue by PhilippKuhlmay** [jweiland-net/maps2#252]
When I try to call the upgrade wizard I get the following error:

`An exception occurred while executing 'SELECT * FROM tx_maps2_domain_model_poicollection pc LEFT JOIN tx_maps2_domain_model_poi p ON pc.uid = p.poicollection WHERE ((p.pid IS NOT NULL) OR (collection_type = ?) OR (collection_type = ?)) AND (pc.deleted = 0)' with params ["Area", "Route"]: Table 'XXX.tx_maps2_domain_model_poi' doesn't exist`

The whole upgrade wizard is not working anymore.
TYPO3 11.5.8
maps2 10.0

**Comment by froemken** [comment]
Hello @PhilippKuhlmay 

thank you for your help. I just have released version 10.0.1 which solves this issue.

Stefan
