### ISSUE TITLE
9.5.11: Class 'TYPO3\CMS\Core\Http\ApplicationType' not found 

### ISSUE THREAD

**Issue by darthnorman** [jweiland-net/maps2#258]
TYPO3\CMS\Core\Http\ApplicationType is used in Classes/Mvc/MapProviderOverlayRequestHandler.php

That class does not exist in TYPO 9.5
I tried maps2 v9.5.11, had to go back to 9.5.9.

**Comment by froemken** [comment]
Hello @darthnorman 

Thank you for your help. I can confirm this issue.
As TYPO3 9 has reached end of support, except ELTS, I had to remove all Tests for TYPO3 9. So it was easy for this bug to find into maps2 ;-)

I hope I will find time to release a new version today. I keep you informed.

Stefan

**Comment by froemken** [comment]
I have just released version 9.3.12 which solves this issue.

Nice greetings

Stefan
