### ISSUE TITLE
Bracketssss

### ISSUE THREAD

**Issue by Sonezi** [jweiland-net/maps2#26]
https://github.com/jweiland-net/maps2/blob/a232320544f44f12e700be65c55320876c500a2b/ext_typoscript_setup.txt#L49

This typo3 finds as execs bracket in file!
If you delete a last bracket the error is gone. :D

**Comment by froemken** [comment]
Ups...what's that?!?! Seems I have copied a little bit too much with my last patch. Sorry. New version is online.

Thank you
