### ISSUE TITLE
Backend MapProvider is not loading with new TYPO3 filesystem-structure (11.5 / 12)

### ISSUE THREAD

**Issue by peterwimmer** [jweiland-net/maps2#265]
With the new filesystem setup in 11.5 / 12 the backend forms for poicollections are not loading because the new assets links "public/_assets/<extensionhash>/" to the Resources/Public folder of an extension is not found.

I don't know what a good solution is, but i fixed it for my setup temporarily with this patch:

[fixPublicResourcePathForOpenStreetMap.txt](https://github.com/jweiland-net/maps2/files/8522695/fixPublicResourcePathForOpenStreetMap.txt)

**Comment by froemken** [comment]
Hello @peterwimmer 

thank you for your help.

Can you explain your issue a little bit more detailed?
Currently I have problems understanding "new filesystem setup". Do you have a TYPO3 ChangeLog link for me?
You wrote "poicollection is not loading". I don't have any problems loading the poicollections in TYPO3 backend or do you mean frontend? Are there any reported warnings or errors? Is there a problem loading the full poicollection record or is it just more a problem loading the map itself?
Have you assigned some images to the record?

Have a nice day

Stefan

**Comment by peterwimmer** [comment]
Hello Stefan,

i was referring to this change:

    https://usetypo3.com/composer-changes-for-typo3-v11-and-v12.html

with this change the filesystem structure looks like this:

> tree -L 1 public  
public
├── _assets
├── browserconfig.xml


> tree -L 1 public/_assets                       
public/_assets
├── 081fa96a07de1dccb64a8a83e1567439 -> ../../vendor/typo3/cms-backend/Resources/Public
├── 14525e5262e0d22d75f200ddba75ef39 -> ../../vendor/typo3/cms-fluid-styled-content/Resources/Public
├── 1ee1d3e909b58d32e30dcea666dd3224 -> ../../vendor/typo3/cms-core/Resources/Public
├── 2076be5e7c25c5348e8257623059b612 -> ../../vendor/jweiland/maps2/Resources/Public
...

and "public/typo3conf/ext" is not there anymore (while switching to new composer mode "typoconf/ext" has to be deleted manually).


The error before the patch gave this error message in  the browser console:

-     Refused to execute script from 'https://xyz.ddev.site/var/www/html/vendor/jweiland/maps2/Resources/Public/JavaScript/Leaflet.js?bust=1650535362' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

-     require.js:5 Uncaught Error: Script error for "leaflet", needed by: TYPO3/CMS/Maps2/OpenStreetMapModule https://requirejs.org/docs/errors.html#scripterror
        at makeError (require.js:5:1799)
        at HTMLScriptElement.onScriptError (require.js:5:17149)

The path "https://xyz.ddev.site/var/www/html/vendor/jweiland/maps2/Resources/Public/JavaScript/Leaflet.js" is not reachable with the structure above.

Hope this helps to identify the issue.

Peter

**Comment by rintisch** [comment]
If this works it would be great to update the documentation which describes how to implement `EXT:maps2` with `EXT:mindshape_cookie_consent` 

In https://github.com/jweiland-net/maps2/blob//master/Documentation/FAQ/Index.rst  on line 109 - 115:

```html
      <ms:consent identifier="google_maps"
                  scripts="{
                      0: '//maps.googleapis.com/maps/api/js?key={settings.googleMapsJavaScriptApiKey}&libraries=places',
                      1: '/typo3conf/ext/maps2/Resources/Public/JavaScript/GoogleMaps2.js',
                      2: '/typo3conf/ext/site_package/Resources/Public/JavaScript/GoogleMaps.js'
                  }">
      </ms:consent>
```

should become 

```html
      <ms:consent identifier="google_maps"
                  scripts="{
                      0: '//maps.googleapis.com/maps/api/js?key={settings.googleMapsJavaScriptApiKey}&libraries=places',
                      1: '{f:uri.resource(path:\'EXT:/maps2/Resources/Public/JavaScript/GoogleMaps2.js\')}',
                      2: '{f:uri.resource(path:\'EXT:site_package/Resources/Public/JavaScript/GoogleMaps.js\')}'
                  }">
      </ms:consent>
```

(see also [Migration to typo3/composer-cms-installers version 4](https://brot.krue.ml/migration-typo3-composer-cms-installers-version-4))
