### ISSUE TITLE
Feature request for other Consent tools, e.g. mindshape_cookie_consent

### ISSUE THREAD

**Issue by DTM-TYPO3** [jweiland-net/maps2#267]
Hello,
I'm using the consent EXT mindshape_cookie_consent [(EXT in repository)](https://extensions.typo3.org/extension/mindshape_cookie_consent) and tried to add a trigger for maps2 but without success.
Could you please integrate a trigger for mindshape?
Thanks in advance!
Stefanie

**Comment by froemken** [comment]
Hello @DTM-TYPO3 

wow...that was damn hard to find a solution and was no fun.

I have just uploaded a new version with an updated FAQ section about mindshape integration:

https://docs.typo3.org/p/jweiland/maps2/main/en-us/FAQ/Index.html#mindshape-cookie-consent

I'm open for better integration ;-)

Nice greetings

Stefan

**Comment by DTM-TYPO3** [comment]
Hi Stefan,
Thank you for your quick help! What is the customization when using OpenStreetMap?

Thanks in advance!
Stefanie
