### ISSUE TITLE
Bootstrap Grids and Maps2

### ISSUE THREAD

**Issue by Sonezi** [jweiland-net/maps2#27]
Good morning @froemken,
maybe this isn't related to your extension at all. The issues is when a put maps plugin in tab(4 tabs) (first part of image) container element from bootstrap grids ext the google map have a trouble finding div to generate map object i guess. When the maps2 plugin is out of tabs container (second part of image) everything is working correctly. 
![maps](https://user-images.githubusercontent.com/18620537/33310509-2421b502-d422-11e7-838a-5785a50bb879.png)
My guess is we need to trigger google.maps.event.trigger(map, 'resize'); event to map regenerate it self on new div size... because on every reaction from browser size map changes to this i think this have something with google map library itself... 
![map2](https://user-images.githubusercontent.com/18620537/33310677-af13e66c-d422-11e7-8ee3-f648592fe758.png) and it's not centered on poi.

Thanks!

**Comment by Sonezi** [comment]
Do you have any suggestion on how to extract coordinates from map?
I found solution to sort the problem with resize, need to extract coordinates from extension so i can fire setCenter() method after new resize.

**Comment by froemken** [comment]
Hello @Sonezi 

thank you for your help.
I have spoken with Jochen Weiland. This is a special FE problem. It is a problem with Google maps, unresolved widths and heighs and Bootstrap. It's not a problem of our extension. In TYPO3 BE we have the same problem with wrong rendered google maps in TCEFORM tabs. We have solved that problem on current master.

Following I have never tested:
You should be able to access all POIs by:
var jsonPois = jQuery(".maps2:first").data("pois");

Then do these resizing stuff, but I currently don't know how to access variable map:
google.maps.event.trigger(map, 'resize');

Next thing is: re-center map position again

if (this.poiCollections.length > 1) {
  this.map.fitBounds(this.bounds);
} else {
  this.map.setCenter(new google.maps.LatLng(this.poiCollections[0].latitude, this.poiCollections[0].longitude));
}

Maybe it is easier to edit our Maps2.js file and implement your own one with TypoScript:

page.includeJSFooter.maps2 = EXT:your_ext/Resources/Public/JavaScript/Maps2.js

Stefan
