### ISSUE TITLE
Only grey background instead of the map within events2 pages

### ISSUE THREAD

**Issue by tzeier** [jweiland-net/maps2#279]
When inserting a map into a tempalte for events2 the map is shown, but only with a grey background instead of the map. 
TYPO3 11, maps2 10.0.7, events2 8.0.1
![image](https://user-images.githubusercontent.com/56545341/183308349-a7b21cac-b847-4662-a4f5-fd69752d42ea.png)
maps partial root path is linked in events2 constants.
Also It doesn't matter whether I try it with Gm or OSM. 
What could be the problem?
Thanks for Your help!

**Comment by froemken** [comment]
If you get a gray backgroud you will get a JavaScript error in your Dev Console of your browser. Maybe you have forgotten to add the static extensino template for maps2 on the site, where you have inserted this events2 plugin. Also check, if API Key ist set on that site.

**Comment by tzeier** [comment]
The only error that appears in the browser console, is, that my favicon couldn't be loaded. But that's another issue... I also made sure to add all the static templates needed and the API are set cortectly. 
Btw. If I insert a map (show POICollection) CE on another page, it works normal. 
The problem only exists, when the map is part of the events2 template (day/Properties.html)

**Comment by froemken** [comment]
Can you please send me a link here or by Slack?

**Comment by tzeier** [comment]
> Can you please send me a link here or by Slack?

Sent it in Slack...

**Comment by sfroemkenjw** [comment]
Hello @tzeier 

seems you have just included the default TS template to your page with events2 and missed to include the TS template for maps2 Google Maps2 as your problem could be solved, if you add the mapTypeId to your template.

As there is no further open question in our slack channel I close this ticket now.

Stefan

**Comment by tzeier** [comment]
Nah, that wasn't the problem. Like I found out in the meantime i had to add some arguments/settings (I think, it was the mapTypeId) to the viewhelper. This wasn't in my template before.  

` <f:render partial="Maps2/PoiCollection" section="showMap"
                      arguments="{poiCollections: {0: location.txMaps2Uid}, override: {settings: {mapWidth: '100%', mapHeight: '200', zoom: '13', mapTypeId: 'google.maps.MapTypeId.ROADMAP', mapTypeControl: '0', streetViewControl: '0', scaleControl: '0', fullScreenControl: '0', zoomControl: '0'}}}" />
`
Works now.

**Comment by sfroemkenjw** [comment]
I have found the problem. It is solved now with maps2 10.0.11 and 11.0.1.

Sytax Error im TypoScript:
https://github.com/jweiland-net/maps2/blob/11.0.0/Configuration/TypoScript/GoogleMaps/setup.typoscript#L31

Nice greetings

Stefan
