### ISSUE TITLE
[bug] wrong absolute file path in POI markers with custom icon

### ISSUE THREAD

**Issue by mzimail** [jweiland-net/maps2#285]
Hi,
after upgrade of TYPO3 and maps2 I have following error:

All previously defined markers that use a custom marker icon have a wrong path in the <img src=""> attribute so that the according icons don't load. 

Actual path output in HTML: https://www.example.com/typo3//typo3/fileadmin/user_upload/img/Kontakt/gruen.png
Correct path to file: https://www.example.com/typo3/fileadmin/user_upload/img/Kontakt/gruen.png

Faulty Environment:
- TYPO3 11.5.21
- maps2 10.0.8
- Migration Wizards of maps2 extension worked flawlessly

Environment that used to work before:
- TYPO3 10.4.22
- maps2 9.3.10

Side notes:
- The problem affects freshly created markers in the identical way
- The problem affects recently uploaded (not migrated) icons in the identical way
- The identical images and icons are displayed flawlessly when used within normal IMG objects within TYPO3 content and not used within scope of a map2 marker
- The problem does not affect POI markers with the default icon assigned that resides in the EXT:map2/... path
- Markers in my case are gathered within a category for displaying multiple markers within one map view

A bugfix or any help for debugging the problem would be highly appreciated.

**Comment by sfroemkenjw** [comment]
Hello @mzimail 

this is IMO an edge-case as you have installed TYPO3 in a sub-folder called "typo3" which is part of the public frontend path.
I have found the issue and solved it in branch typo3_12_compatibility. So, with next major release this issue is solved.

Stefan
