### ISSUE TITLE
Use InfoWindowContent.html in InfoWindowContent.php (backend preview) 

### ISSUE THREAD

**Issue by derBoogie** [jweiland-net/maps2#286]
I've overwritten the InfoWindowContent.html because to remove titleWrapper and addressWrapper, to show only the info window content in frontend maps.
To make the backend preview fit, the InfoWindowContent.html should be used in InfoWindowContent.php.

**Comment by sfroemkenjw** [comment]
Hello @derBoogie 

I can not use the html file for backend form rendering. This part is called FieldWizard which has just a limited amount of allowed tags. Here are the two lines of TYPO3 backend PHP source:

```
$allowedTags = '<a><br><br/><div><em><i><p><strong><span><code>';
if (strip_tags($informationResult['html'], $allowedTags) !== $informationResult['html']) {
```

So, if you add an image or other elements, it will never display the same like in frontend. In your case it may make more sense to disable the wizard `maps2InfoWindowContent` in TCA/Overrides of your extension.

Stefan
