### ISSUE TITLE
[BUG] Typo3temp/assets/compressed get bigger and bigger

### ISSUE THREAD

**Issue by hloens** [jweiland-net/maps2#288]
Typo3temp/assets/compressed get bigger and bigger, because the merged js is made several time per minute. 
If you have concat activate for javascript files (`config.concatenateJs = 1`), every time maps2 integrates the javascript file from the google api and google gives the file everytime a new modification time and a new concated javascript file is created. 
Solution is add in the file „`maps2/Configuration/TypoScript/GoogleMaps/setup.typoscript`“ the typescript code „`page.includeJSFooterlibs.googleMapsForMaps2.excludeFromConcatenation = 1`“ to stop integration of the google api js file.

**Comment by sfroemkenjw** [comment]
Hello @hloens 

thank you for your help. I have implemented that line to current main branch.

Stefan

**Comment by sfroemkenjw** [comment]
I add some buzz words to find that ticket much faster.

It has something to to with a timestamp in included Google Maps JavaScript files

The compress / compressed folder typo3temp folder grows very fast and gets really huge

**Comment by sfroemkenjw** [comment]
Problem exists in TYPO3 8.7
Problem exists in TYPO3 9.5
