### ISSUE TITLE
Marker-Clustering

### ISSUE THREAD

**Issue by rasgor** [jweiland-net/maps2#29]
Dear Stefan,

are there any plans of adding marker-clustering as an option to the extension yet?

https://developers.google.com/maps/documentation/javascript/marker-clustering?hl=de

**Comment by froemken** [comment]
Hello @rasgor 

we currently have no plan to do this. But next version will collect all GoogleMaps in a global reachable array variable. So you can access each map and hopefully add that feature with your own JavaScript. I will not close this ticket now, as I will try this feature on my own.

Stefan

**Comment by froemken** [comment]
Feature is just in Travis. With a little bit of luck it will be in master in half an hour

**Comment by froemken** [comment]
OK...It's done.

Have fun with the new feature

Stefan

**Comment by rasgor** [comment]
Awsome, I'll give it a try later this week. 

Thank you very much 🥇

**Comment by froemken** [comment]
It's not activated by default. Please visit Constants Editor and activate MarkerClustering Checkbox.
