### ISSUE TITLE
No parameter in initialize view TYPO3 7 LTS

### ISSUE THREAD

**Issue by pascal20997** [jweiland-net/maps2#3]
First parameter of initializeView() has to be 

> TYPO3\CMS\Extbase\Mvc\View\ViewInterface

 but is not given. This throws a PHP warning.

> #1: PHP Warning: Declaration of JWeiland\Maps2\Controller\AbstractController::initializeView() should be compatible with TYPO3\CMS\Extbase\Mvc\Controller\ActionController::initializeView(TYPO3\CMS\Extbase\Mvc\View\ViewInterface $view) in /Users/prinker/mampProjects/htdocs/typo3master_1/typo3conf/ext/maps2/Classes/Controller/AbstractController.php line 30

**Comment by froemken** [comment]
Very good. Thank you for that hint. It was solved with version 2.3.0
