### ISSUE TITLE
Osm Geocode URI: File not found: API no longer accessible via this URL

### ISSUE THREAD

**Issue by MatthiasRixen** [jweiland-net/maps2#303]
Hi,

since a couple of days I get following Error:

`Client error: GET https://nominatim.openstreetmap.org/search/K%C3%B6ln?format=json&addressdetails=1 resulted in a 404 Not Found response: <html> <head> <title>File Not Found</title> </head> <body> <h1>File not found: API no longer accessible via this URL</h1 (truncated...) `

Current OpenStreetMap Geocode URI is: 
https://nominatim.openstreetmap.org/search/%s?format=json&addressdetails=1

If you open the Geocode URI with request

for emaple: https://nominatim.openstreetmap.org/search/K%C3%B6ln?format=json&addressdetails=1

you get the following:

> 
> File not found: API no longer accessible via this URL
> Using the URL /search/ and /reverse/ (with slashes) is no longer supported. Please use URLs as given in the documentation.
> Examples how to change the URL:
> You use: https://nominatim.openstreetmap.org/search/?q=Berlin
> Change to: https://nominatim.openstreetmap.org/search?q=Berlin
> You use: https://nominatim.openstreetmap.org/search/US/Texas/Huston
> Change to: https://nominatim.openstreetmap.org/search?q=Huston, Texas, US
> See github issue #3134 for more details.

Is the error already known or is something wrong with the Configuration? Nothing changed in the System. No Updates where made ...

Thx!

**Comment by MatthiasRixen** [comment]
Hello,

I found the error myself. I changed the formatting of the URL like this:

https://nominatim.openstreetmap.org/search?q=%s&format=json&addressdetails=1

Now it's working again!

**Comment by sfroemkenjw** [comment]
I can't find anything regarding this change at Nominatim website, but yes, it seems the URI has changed. I will re-open the issue ticket. The URI has to be updated in maps2.

PS: In OpenStreetMapModule I already use the new correct URI, but in extension settings it's still the old one.

Stefan

**Comment by sfroemkenjw** [comment]
Hint for me: Just changing the URI is not enough! I have to create a new UpgradeWizard to check, if URI is still exactly the old one (or empty) and update that URI with the new version.

**Comment by sfroemkenjw** [comment]
@joeschi 
Thank you. I have just released version 10.0.10
