### ISSUE TITLE
Call to a member function count() on array in \JWeiland\Maps2\Controller\PoiCollectionController::multipleResultsAction

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/maps2#33]
If the geocoding fails, the returned value is not the expected one

**Comment by froemken** [comment]
I just have implemented a new GoogleMapsClient. With this patch your issue is also gone, but not completely finished:
https://github.com/jweiland-net/maps2/pull/53/files

I'll keep this issue open until I'm done completely.

Stefan

**Comment by froemken** [comment]
Ok...new API calls are implemented. Job is done.
