### ISSUE TITLE
Add more chash excluded parameters

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/maps2#34]
IMO those 2 needs to be added as well

```
    $GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'][] = 'tx_maps2_searchwithinradius[search][address]';
    $GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'][] = 'tx_maps2_searchwithinradius[controller]';
```

**Comment by froemken** [comment]
tx_maps2_searchwithinradius[search][address] is already part of ext_localconf.php.
What is your goal excluding controller from cHash calculation? I don't understand the benefit. Instead it may be better to remove controller completely and set it as default Controller in TS.

**Comment by georgringer** [comment]
I had issues in 8.7 and worked after fixing it

**Comment by froemken** [comment]
I just have removed these excludeParameters lines for this plugin, because it's a POST request now.
