### ISSUE TITLE
Use templateRootPaths instead of templateRootPath

### ISSUE THREAD

**Issue by georgringer** [jweiland-net/maps2#37]
Instead of the deprecated templateRootPath, use templateRootPaths, same for layouts + partials

**Comment by froemken** [comment]
Oh. Job ist done since 20. April 2018:

https://github.com/jweiland-net/maps2/commit/bcf15307a6172dd27a6f39543d57a7b1685375e8#diff-235996eb874e032d98fa3cd5c46cdb53

Thank you and have fun

Stefan
