### ISSUE TITLE
Allow configuration of InfoWindow template

### ISSUE THREAD

**Issue by Kephson** [jweiland-net/maps2#6]
If I'm right, it is not possible to configure the path of the InfoWindowContent template.
https://github.com/jweiland-net/maps2/blob/master/Classes/Controller/AbstractController.php#L114
https://github.com/jweiland-net/maps2/blob/master/Classes/ViewHelpers/Widget/Controller/AbstractController.php#L94
It would be helpful to have a configuration option for the template.

**Comment by froemken** [comment]
Oh...you're right. Please give me a day or two to fix this. OK?

**Comment by froemken** [comment]
Good luck. I just got some time and have uploaded a new version: 2.4.0.

**Comment by Kephson** [comment]
thanks, you're my hero ;-)
