### ISSUE TITLE
Uncaught TYPO3 Exception

### ISSUE THREAD

**Issue by edley07** [jweiland-net/maps2#66]
Error appears since update to TYPO3 8.7.17 ?

#1289386765: Could not analyse class: "JWeiland\Maps2\Utility\GeocodeUtility" maybe not loaded or no autoloader? Class JWeiland\Maps2\Utility\GeocodeUtility does not exist

**Comment by wowawebdesign** [comment]
Errors is also in 7.6.30 with maps2 4.1.0

**Comment by froemken** [comment]
This has nothing to do with this extension. Please use search here in Github and try to find GeocodeUtility in this repository. You will only find one entry in ChangeLog:

https://github.com/jweiland-net/maps2/search?q=GeocodeUtility&unscoped_q=GeocodeUtility

I currently have not updated all the other extensions like events2, clubdirectory, yellowpages2, ... which may still try to call GeocodeUtility. Can you please check, if you use one of these extensions?

Stefan

**Comment by edley07** [comment]
Yes, i use events2 in combination with maps2

Andre

**Comment by froemken** [comment]
Ok. Thank you. I will try to update events2 this week

**Comment by froemken** [comment]
I have just uploaded a patch to master Branch of events2 solving this issue. I will create a new version at the end of this week.
