### ISSUE TITLE
A cache with identifier "maps2_registry" does not exist.

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/maps2#74]
While trying to install maps2 v4.2.5 I get the error message above. 

`in /html/typo3/typo3conf/ext/maps2/Classes/Tca/Maps2Registry.php line 73`

```
// As this constructor will only be called once after clearing SystemCache
        // we can securely remove all registered fields
        $this->maps2RegistryCache = GeneralUtility::makeInstance(CacheManager::class)
            ->getCache('maps2_registry');

        $this->template = str_repeat(PHP_EOL, 3) . 'CREATE TABLE %s (' . PHP_EOL
            . '  %s int(11) unsigned DEFAULT \'0\' NOT NULL' . PHP_EOL . ');' . str_repeat(PHP_EOL, 3);

```

Regards
Hobokens

--------
TYPO3 9.5.3

**Comment by froemken** [comment]
Interessting. I habe registered that Cache in ext_localconf.php so clear system cache or all caches and you should be done

**Comment by froemken** [comment]
Got it. Error appears in extension manager while activating the extension. Damn. I'm in train now for next 4 hours. Hope I will find a solution.

**Comment by Hobokens** [comment]
Hi Stefan,
thanks for your support. When I try to install the new maps2 version from github I get the following strange error message


```
(1/1) #30 Doctrine\DBAL\Schema\SchemaException

There is no column with name 't3ver_oid' on table 'tt_address'.
```

And in the log is the message:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'JWeiland\Maps2\Tca\Maps2Registry' not found | Error thrown in file /html/typo3/typo3conf/ext/events2/Configuration/TCA/Overrides/tx_events2_domain_model_location.php in line 8. Requested URL: http://my-domain.de/typo3/index.php?route=%%2Fajax%%2Fsystem-information%%2Frender&token=--AnonymizedToken--&skipSessionUpdate=1 `

Regards Hobokens

**Comment by froemken** [comment]
Missing column in tt_address? Yeah! That’s strange. I have installed events2 and maps2 here in various order. No error. No log entry with TYPO3 9. Do you use Composer?

**Comment by froemken** [comment]
Ok...I have setup a non-composer based installation and I can confirm that bug. Strange: If you install maps2 everything works. No error. If you now install tt_address all columns of ext_tables.sql will not be created which results into that error. Currently I don't know why these columns were not created. Hey xdebug...ready for a walk ;-)

**Comment by froemken** [comment]
I have just pushed version 4.2.7 to Github and TER where tt_address will be suggested. This is needed to build a correct extension ordering in PackageStates and CREATE TABLE array of TYPO3: https://forge.typo3.org/issues/87535?next_issue_id=87534

**Comment by froemken** [comment]
Please install maps2 4.2.8 as I have found another bug with TYPO3 9. With version 4.2.7 column UID could not be created, as table tt_address already exists. IMHO this is a bug in TYPO3: https://forge.typo3.org/issues/87537
With maps2 4.2.8 I have switched over to Maps2Registry to create tx_maps2_uid in tt_address, which does not have theses side-effects.

Stefan

**Comment by Hobokens** [comment]
Sorry, never ending story. I just discovered that I get an error now when I try to save a location data in events2:
`An exception occurred while executing 'SELECT `tx_maps2_uid` FROM `tx_events2_domain_model_location` WHERE `uid` = ?' with params [4]: Unknown column 'tx_maps2_uid' in 'field list' `

I cleared all caches in install tool and installed maps2 v4.2.8 from ter.

Regards
Hobokens

**Comment by froemken** [comment]
With 4.2.8 I have updated documentation: https://docs.typo3.org/typo3cms/extensions/maps2/4.2.8/DeveloperManual/Maps2Registry/Index.html

Please use Database Compare in Installtool to add the missing column.

**Comment by Hobokens** [comment]
I used Database Compare but it doesn't offer the opportunity to add the missing column. I also uninstalled and installed again events2 and maps2 without the expected result. 

Regards
Hobokens

**Comment by froemken** [comment]
Third TYPO3 ticket: https://forge.typo3.org/issues/87546

While installing maps2 the CacheManager configuration of my ext_localconf.php will be added to TYPO3_CONF_VARS, but it will not be registered in CacheManager itself. So, while processing TCA and Overrides, maps2 Cache could not be found. I have re-registered TYPO3 Caches on my own now. Hope it will be solved by TYPO3 in future.

Version 4.2.9 is now available

Stefan

**Comment by Hobokens** [comment]
The problem is solved - thanks !

Regards
Hobokens
