### ISSUE TITLE
No Markericon width maps2:widget.poiCollection

### ISSUE THREAD

**Issue by kaialt** [jweiland-net/maps2#80]
There is no Marker in the Map when I use maps2:widget.poiCollection width a custom Markericon. Testet width Category an POI. In the view width pluginmode everthing is fine. Without the Customicon, the Map width maps2:widget.poiCollection shows the correct Standardicon.

Update: The problem only appears with realurl and baseurl is not set, so the uri to the icon is wrong.

**Comment by froemken** [comment]
Hey @kaialt 

thank you for your bug report.
I just have found many bugs regarding this issue and published new version 5.1.0.
In case of URLs with directories like ../extensions/maps/show.html a markerIcon with fileadmin/user_upload/test.png will be appended to the directory. So it results in ../extensions/maps/fileadmin/user_upload/test.png, which is wrong.
For now I prepend the current SiteUrl to the Iconpath which solved this problem.

Nice greetings

Stefan
