### ISSUE TITLE
`placeIdOnly` is deprecated

### ISSUE THREAD

**Issue by Bellatrixnia** [jweiland-net/maps2#81]
> Autocomplete: `placeIdOnly` is deprecated as of January 15, 2019, and will be turned off on January 15, 2020. Use `fields: ['place_id', 'name', 'types']` instead.

Got this message in my google chrome terminal after creating a new item.

**Comment by froemken** [comment]
Perfect. Thank you. I have just repaired that:

https://github.com/jweiland-net/maps2/pull/83

Version 4.3.3

Stefan
