### ISSUE TITLE
The GeoCode URL is not configurable

### ISSUE THREAD

**Issue by vkemeter** [jweiland-net/maps2#86]
the uri, which is defined in the GeoCodeRequest class (property $uri) is at the moment not configurable. it would be nice, to add there components. e.g. components=country:AT.

the benefit is, that if an user is searching for zip codes (eg in austria) you can restrict the geocode api to search in austria and not all over the world. google will return for eg 2351 some address in san francisco instead of lower austria, mödling.

**Comment by froemken** [comment]
Currently you can try to configure default country in ExtensionManager Configuration. This value will be added to ALL of your queries. Maybe it helps you.

**Comment by froemken** [comment]
With version 5.2.0 you can now configure Geocode URI of Google Maps and OpenStreetMap:

https://extensions.typo3.org/extension/maps2/

New version will be online within the next 15 minutes

Stefan
