### ISSUE TITLE
Only a few default zoom-levels in OSM seems to be possible

### ISSUE THREAD

**Issue by rumpfwerk** [jweiland-net/maps2#98]
Tried the extension on 9.5.5 with bootstrap package with OSM, default map provider. 
(same behaviour with other map providers, I tried)
Only the default zoom-levels 12, 17, 18 are possible (I did not try lower than 12).

Other Zoomlevels, e.g. 13, are showing some position in the atlantik. 

strange...

**Comment by froemken** [comment]
Thank you for your report.
I have set zoom level after map creation. As setZoom() will start an animation it seems that an async call was created with wrong latitude/longitude. I have implemented zoom level directly into map creation which seems to solve that problem.

Stefan
